apiVersion: v1
kind: Service
metadata:
  labels:
    name: monitoring-influxdb
  name: monitoring-influxdb
spec:
  type: NodePort
  ports:
  - name: http
    port: 8083
    targetPort: 8083
    nodePort: 30083
  - name: api
    port: 8086
    targetPort: 8086
    nodePort: 30086
  selector:
    name: influxdb